### ISSUE TITLE
Assing read and write permission when send link 

### ISSUE THREAD

**Issue by Dnhatsave** [zylklab/alfresco-share-send-link-by-email#3]
Hi @CesarCapillas  ,

first off all i like to congratulate for share this useful feature, 
i know that this isn't a issue, but a new implementation request for assign read or write permission for the recipients of link, i would like to know how can i achieve that goal? is that possible ?

appreciate your help.
Dnhatsave.

**Comment by CesarCapillas** [comment]
Hi,

Thanks for your message.
Repo actions are out of scope in this addon, because in this case, you are simply opening an external email client via desktop protocol for providing link via email. 

You could do something in that direction, if repo action is able to check user and email data, from custom metadata, or Alfresco input form in Share.

Kind regards.
--C.

**Comment by Dnhatsave** [comment]
oky thanks for response.
I'll do this way.
